variable "aws_region" {
  type        = string
  description = "Region for AWS Resources"
  default     = "us-east-2"
}


variable "company" {
  type        = string
  description = "Company name for resource tagging"
  default     = "Ringier"
}

variable "project" {
  type        = string
  description = "Project name for resource tagging"
  default     = "challenge"
}

variable "enable_dns_hostnames" {
  type        = bool
  description = "Enable DNS hostnames in VPC"
  default     = true
}

variable "enable_map_public_ip" {
  type        = bool
  description = "Enable DNS hostnames in VPC"
  default     = true
}

variable "vpc_cidr_block" {
  type        = string
  description = "Base CIDR Block for VPC"
  default     = "100.0.0.0/16"
}

variable "allow_anywhere" {
  type        = string
  description = "allow request from anywhere"
  default     = "0.0.0.0/0"
}

variable "bostion-server-sg-description" {
  type    = string
  default = "Allowed types HTTP, PING, SSH"
}

variable "vpc_subnets_cidr_blocks" {
  type        = list(string)
  description = "CIDR Blocks for Subnets in VPC"
  default     = ["100.0.0.0/24", "100.0.1.0/24"]
}

variable "map_public_ip_on_launch" {
  type        = bool
  description = "Map a public IP address for Subnet instances"
  default     = true
}

variable "instance_type" {
  type        = string
  description = "Type for EC2 Instance"
  default     = "m6g.medium"
}


variable "ami_type" {
  type = string
  default = "ami-001321a85978afa12"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}



